version: "3.9"
services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ../actor1_ecologique:/actor1_ecologique
      - ../actor2_mobilites:/actor2_mobilites
      - ../actor3_securite:/actor3_securite
    depends_on:
      - mlflow
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000

  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    ports:
      - "5000:5000"
    volumes:
      - ./mlflow/mlruns:/mlflow/mlruns
    command: >
      mlflow server
      --host 0.0.0.0
      --port 5000
      --backend-store-uri /mlflow/mlruns
      --default-artifact-root /mlflow/mlruns
