"""
Actor 1 — Transition Écologique
================================
Wraps inference for:
  - co2         : XGBoost regression → CO2 emissions prediction
  - energy      : XGBoost regression → energy usage prediction
  - cluster     : K-Means clustering → pollution zone label

All models are loaded lazily and cached in-process for performance.
Model files must exist in actor1_ecologique/outputs/ (generated by main.py).

Path resolution:
  This file lives at  ml_api/actors/actor1.py
  Going 3 levels up → Desktop/
  Model base dir    → Desktop/actor1_ecologique/outputs/
"""

import logging
import pickle
import threading
from pathlib import Path
from typing import Any, Dict

logger = logging.getLogger("ml_api.actor1")

# ── Absolute path — works regardless of CWD where uvicorn is launched ─────────
# actor1.py → actors/ → ml_api/ → Desktop/
BASE = Path(__file__).resolve().parent.parent.parent / "actor1_ecologique" / "outputs"

# ── Thread-safe lazy model cache ───────────────────────────────────────────────
_cache: Dict[str, Any] = {}
_lock = threading.Lock()


def _load(filename: str) -> Any:
    """Load a .pkl file from actor1 outputs, with in-memory caching."""
    key = str(filename)
    if key not in _cache:
        with _lock:
            if key not in _cache:
                path = BASE / filename
                if not path.exists():
                    raise FileNotFoundError(
                        f"Actor1 model file not found: {path}. "
                        "Run actor1_ecologique/main.py to train models."
                    )
                logger.info(f'"Actor1: loading {filename}"')
                with open(path, "rb") as f:
                    _cache[key] = pickle.load(f)
    return _cache[key]


# ── Public interface ───────────────────────────────────────────────────────────
def predict(task: str, data: dict) -> Any:
    """
    Run inference for actor1.

    Parameters
    ----------
    task : str
        One of: 'co2', 'energy', 'cluster'
    data : dict
        Must contain a 'features' dict with required keys.

    Returns
    -------
    float | dict
        co2 / energy → float
        cluster      → {"cluster": int}
    """
    features: dict = data.get("features", {})

    # ── CO2 Regression ────────────────────────────────────────────────────────
    if task == "co2":
        model = _load("xgboost_co2.pkl")
        feature_list = _load("xgboost_features.pkl")

        _warn_missing(features, feature_list, task)
        X = [[features.get(f, 0) for f in feature_list]]
        result = float(model.predict(X)[0])

        logger.info(f'"Actor1 co2: result={result:.4f}"')
        return result

    # ── Energy Regression ─────────────────────────────────────────────────────
    elif task == "energy":
        model = _load("xgboost_nrj.pkl")
        feature_list = _load("xgboost_features.pkl")

        _warn_missing(features, feature_list, task)
        X = [[features.get(f, 0) for f in feature_list]]
        result = float(model.predict(X)[0])

        logger.info(f'"Actor1 energy: result={result:.4f}"')
        return result

    # ── Pollution-Zone Clustering ─────────────────────────────────────────────
    elif task == "cluster":
        model = _load("kmeans_pollution_zones.pkl")
        scaler = _load("clustering_scaler.pkl")

        import numpy as np

        if not features:
            raise ValueError("Actor1 cluster task requires at least one feature value.")

        X_vals = list(features.values())
        X_scaled = scaler.transform([X_vals])
        cluster_label = int(model.predict(X_scaled)[0])

        logger.info(f'"Actor1 cluster: cluster_label={cluster_label}"')
        return {"cluster": cluster_label}

    else:
        raise ValueError(
            f"Unknown task '{task}' for actor1. "
            "Valid tasks: ['co2', 'energy', 'cluster']"
        )


def _warn_missing(features: dict, required: list, task: str) -> None:
    """Log a warning for any required features that are missing (filled with 0)."""
    missing = [f for f in required if f not in features]
    if missing:
        logger.warning(
            f'"Actor1 {task}: missing features {missing} — defaulting to 0"'
        )